name: Update GH Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs_src/**
  # pull_request:
    # The branches below must be a subset of the branches above
  #  branches: [ "main" ]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: |
          pip install mkdocs "mkdocs-material>=8.2" "mkdocs-htmlproofer-plugin>=0.8"
          pip install "mkdocs-swagger-ui-tag" "mkdocstrings>=0.24.3" "mkdocstrings-python>=1.9.2"     
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Build Site with MkDocs
        run: mkdocs build --config-file mkdocs.yml
      - name: Deploy
        run: mkdocs gh-deploy --force --clean --verbose
